### PR TITLE
Direction overlay

### PR DESCRIPTION
**Pull request by stevenqha**
Currently the overlay is working and has been set to decrement the heading angle for testing. The direction calculations have been commented out and is still a work in progress

### CODE REVIEW

**Comment by wmmc88** [comment]
I fixed some small issues @stevenqha . pull the changes and delete any uncommitted changes/files/folders on your local branch and rebuild. make sure i didnt break anything lol

**Comment by wmmc88** [comment]
@stevenqha download a clean copy of the repo and confirm it still works pls.

**Comment by stevenqha** [comment]
It works fine

**Comment by wmmc88** [comment]
0 is east

**Comment by stevenqha** [comment]
Okay. The node should be able to get correct heading from the gps now

**Review by wmmc88 — APPROVED** [review]

**Pull request merged**
